var ow1Data = {
    Dva: {
      type: "tank",
      counters: {
        Ana: "+",
        Ashe: "+",
        Bastion: "+",
        Brigitte: "-",
        Doomfist: "-",
        Hanzo: "++",
        Junkrat: "-",
        McCree: "+",
        Mei: "-",
        Mercy: "++",
        Moira: "+",
        Pharah: "+",
        //Reaper: "-",
        Sombra: "-",
        Widowmaker: "++",
        Zarya: "--"
      },
      difficulty: 2,
      skill: 2,
    },
    Orisa: {
      type: "tank",
      counters: {
        Ashe: "+",
        Doomfist: "+",
        Genji: "-",
        Hanzo: "-",
        Moira: "-",
        Reaper: "-",
        Torbjorn: "+",
        Widowmaker: "+"
      },
      difficulty: 2,
      skill: 2,
    },
    Reinhardt: {
      type: "tank",
      counters: {
        Bastion: "--",
        Brigitte: "-",
        Doomfist: "-",
        Junkrat: "--",
        Mei: "--",
        Orisa: "-",
        Pharah: "--",
        Reaper: "--",
        Soldier76: "+",
        Sombra: "-",
        Widowmaker: "+"
      },
      difficulty: 1,
      skill: 1,
    },
    Roadhog: {
      type: "tank",
      counters: {
        Ana: "-",
        Baptiste: "+",
        Bastion: "+",
        Echo: "+",
        Lucio: "+",
        McCree: "+",
        Mei: "--",
        Reaper: "--",
        Sigma: "-",
        Soldier76: "+",
        Sombra: "+",
        Widowmaker: "-",
        Winston: "++",
        WreckingBall: "+",
        Zarya: "-"
      },
      difficulty: 1,
      skill: 1,
    },
    Sigma: {
      type: "tank",
      counters: {
        Ana: "+",
        Doomfist: "-",
        Lucio: "-",
        Roadhog: "+",
        Sombra: "-"
      },
      difficulty: 3,
      skill: 3,
    },
    Winston: {
      type: "tank",
      counters: {
        Bastion: "-",
        Dva: "++",
        Genji: "++",
        McCree: "+",
        Reaper: "--",
        Roadhog: "--",
        Symmetra: "+",
        Widowmaker: "++",
        Zenyatta: "++"
      },
      difficulty: 2,
      skill: 2,
    },
    WreckingBall: {
      type: "tank",
      counters: {
        Ana: "-",
        Brigitte: "--",
        Mei: "-",
        Reaper: "-",
        Roadhog: "-",
        Sombra: "--",
        Widowmaker: "+"
      },
      difficulty: 3,
      skill: 3,
    },
    Zarya: {
      type: "tank",
      counters: {
        Bastion: "-",
        Dva: "++",
        Genji: "++",
        Junkrat: "+",
        Mei: "+",
        Pharah: "--",
        Reaper: "-",
        Roadhog: "+",
        Torbjorn: "++",
        Zenyatta: "-"
      },
      difficulty: 3,
      skill: 3,
    },
    Ashe: {
      type: "dps",
      counters: {
        Ana: "-",
        Brigitte: "+",
        Dva: "+",
        Doomfist: "+",
        Hanzo: "-",
        Junkfist: "+",
        Mei: "+",
        Mercy: "+",
        Orisa: "-",
        Pharah: "++",
        Reaper: "+",
        Soldier76: "+",
        Symmetra: "+",
        Widowmaker: "-",
        Winston: "-",
        WreckingBall: "-"
      },
      difficulty: 2,
      skill: 2,
    },
    Bastion: {
      type: "dps",
      counters: {
        Ana: "-",
        Dva: "-",
        Echo: "+",
        Genji: "-",
        Hanzo: "-",
        Junkrat: "-",
        Reinhardt: "++",
        Roadhog: "-",
        Soldier76: "-",
        Tracer: "-",
        Widowmaker: "-",
        Winston: "++",
        Zarya: "+"
      },
      difficulty: 1,
      skill: 1,
    },
    Doomfist: {
      type: "dps",
      counters: {
        Ashe: "-",
        Dva: "+",
        Genji: "+",
        McCree: "-",
        Orisa: "-",
        Pharah: "--",
        Reinhardt: "+",
        Sigma: "+",
        Soldier76: "-",
        Sombra: "--"
      },
      difficulty: 3,
      skill: 3,
    },
    Echo: {
      type: "dps",
      counters: {
        Ana: "-",
        Bastion: "-",
        Baptiste: "-",
        McCree: "-",
        //Mei: "-",
        Roadhog: "-",
        Soldier76: "-",
        Sombra: "-"
        //Tracer: "+*",
        //Widowmaker: "-*"
      },
      difficulty: 2,
      skill: 2,
    },
    Genji: {
      type: "dps",
      counters: {
        Bastion: "+",
        Brigitte: "-",
        Doomfist: "-",
        Hanzo: "++",
        Mercy: "++",
        Orisa: "+",
        Pharah: "-",
        Widowmaker: "++",
        Winston: "--",
        Zarya: "--"
      },
      difficulty: 3,
      skill: 3,
    },
    Hanzo: {
      type: "dps",
      counters: {
        Ashe: "+",
        Bastion: "+",
        Dva: "--",
        Genji: "--",
        Orissa: "+",
        Sombra: "+",
        Torbjorn: "+",
        Tracer: "--",
        Widowmaker: "-"
      },
      difficulty: 3,
      skill: 3,
    },
    Junkrat: {
      type: "dps",
      counters: {
        Bastion: "+",
        Brigitte: "+",
        Dva: "+",
        Pharah: "--",
        Reaper: "+",
        Reinhardt: "++",
        Sombra: "+",
        Torbjorn: "++",
        Tracer: "+",
        Widowmaker: "--",
        Zarya: "-"
      },
      difficulty: 2,
      skill: 2,
    },
    McCree: {
      type: "dps",
      counters: {
        Dva: "-",
        Doomfist: "+",
        Echo: "+",
        Lucio: "++",
        Mei: "-",
        Mercy: "+",
        Pharah: "++",
        Roadhog: "-",
        Sombra: "+",
        Symmetra: "+",
        Tracer: "+",
        Widowmaker: "-",
        Winston: "-"
      },
      difficulty: 2,
      skill: 2,
    },
    Mei: {
      type: "dps",
      counters: {
        Ashe: "-",
        Dva: "+",
        //Echo: "+",
        Lucio: "-",
        McCree: "+",
        Pharah: "-",
        Reinhardt: "++",
        Roadhog: "++",
        Widowmaker: "-",
        WreckingBall: "+",
        Zarya: "-"
      },
      difficulty: 3,
      skill: 3,
    },
    Pharah: {
      type: "dps",
      counters: {
        Ana: "-",
        Ashe: "-*",
        Brigitte: "++",
        Dva: "-",
        Doomfist: "++",
        Genji: "+",
        Junkrat: "++",
        McCree: "--",
        Mei: "+",
        Reaper: "++",
        Reinhardt: "++",
        Soldier76: "--",
        Symmetra: "++",
        Widowmaker: "-"
      },
      difficulty: 1,
      skill: 1,
    },
    Reaper: {
      type: "dps",
      counters: {
        Ana: "-",
        //Dva: "+",
        Junkrat: "-",
        Orisa: "+*",
        Pharah: "--",
        Reinhardt: "++",
        Roadhog: "++",
        Sombra: "+",
        Winston: "++",
        WreckingBall: "+",
        Zarya: "+",
        Zenyatta: "++"
      },
      difficulty: 1,
      skill: 1,
    },
    Soldier76: {
      type: "dps",
      counters: {
        Bastion: "+",
        Doomfist: "+",
        Echo: "+",
        Pharah: "++",
        Reinhardt: "-",
        Torbjorn: "++"
      },
      difficulty: 1,
      skill: 1,
    },
    Sombra: {
      type: "dps",
      counters: {
        Ana: "+",
        Brigitte: "+",
        Dva: "+",
        Doomfist: "++",
        Echo: "+",
        Hanzo: "-",
        Junkrat: "-",
        Lucio: "+",
        McCree: "-",
        Reaper: "-",
        Reinhardt: "+",
        Roadhog: "-",
        Symmetra: "+",
        Tracer: "++",
        WreckingBall: "++",
        Zenyatta: "+"
      },
      difficulty: 3,
      skill: 3,
    },
    Symmetra: {
      type: "dps",
      counters: {
        McCree: "-",
        Pharah: "--",
        Sombra: "-",
        //Tracer: "+*",
        Winston: "--",
        Reinhardt: "+"
      },
      difficulty: 2,
      skill: 2,
    },
    Torbjorn: {
      type: "dps",
      counters: {
        Ana: "-",
        Genji: "+",
        Hanzo: "--",
        Junkrat: "--",
        Orisa: "-",
        Soldier: "--",
        Tracer: "+",
        Widowmaker: "--",
        Zarya: "--"
      },
      difficulty: 2,
      skill: 2,
    },
    Tracer: {
      type: "dps",
      counters: {
        Bastion: "+",
        Brigitte: "-",
        Hanzo: "++",
        Junkrat: "-",
        McCree: "-",
        Pharah: "-",
        Sombra: "--",
        Torbjorn: "-",
        Zenyatta: "++"
      },
      difficulty: 2,
      skill: 2,
    },
    Widowmaker: {
      type: "dps",
      counters: {
        Bastion: "+",
        Dva: "--",
        //Echo: "+*",
        Genji: "--",
        Hanzo: "-",
        Junkrat: "++",
        McCree: "+",
        Mei: "+",
        Orisa: "-",
        Pharah: "+",
        Reinhardt: "-",
        Sombra: "-",
        Torbjorn: "+",
        Winston: "--",
        WreckingBall: "-"
      },
      difficulty: 2,
      skill: 2,
    },
    Ana: {
      type: "healer",
      counters: {
        Ashe: "+",
        Baptiste: "+*",
        Bastion: "+",
        Dva: "-",
        Echo: "+",
        Lucio: "+",
        Moira: "+",
        Pharah: "+",
        Reaper: "+",
        Roadhog: "+",
        Sigma: "-",
        Sombra: "-",
        Winston: "-",
        WreckingBall: "+",
        Zenyatta: "+"
      },
      difficulty: 3,
      skill: 3,
    },
    Baptiste: {
      type: "healer",
      counters: {
        Ana: "-*",
        Doomfist: "+",
        Dva: "+*",
        Echo: "+",
        //Junkrat: "+*",
        Roadhog: "+",
        Sombra: "-",
        Soldier: "-*"
        //Tracer: "+*"
      },
      difficulty: 3,
      skill: 3,
    },
    Brigitte: {
      type: "healer",
      counters: {
        Ashe: "-",
        Dva: "+",
        Genji: "+",
        Junkrat: "-",
        Pharah: "--",
        Reaper: "-",
        Reinhardt: "+",
        Sombra: "-",
        Tracer: "+",
        WreckingBall: "++"
      },
      difficulty: 1,
      skill: 1,
    },
    Lucio: {
      type: "healer",
      counters: {
        Ashe: "-",
        McCree: "--",
        Mei: "+",
        Roadhog: "-",
        Sigma: "+",
        Sombra: "-"
      },
      difficulty: 2,
      skill: 2,
    },
    Mercy: {
      type: "healer",
      counters: {
        Ashe: "-",
        Dva: "--",
        Genji: "--",
        McCree: "-"
      },
      difficulty: 1,
      skill: 1,
    },
    Moira: {
      type: "healer",
      counters: {
        Ana: "-",
        Dva: "-",
        Orisa: "+",
        Reinhardt: "+"
      },
      difficulty: 2,
      skill: 2,
    },
    Zenyatta: {
      type: "healer",
      counters: {
        Ana: "-",
        Reaper: "--",
        Sombra: "-",
        Tracer: "--",
        Zarya: "+"
      },
      difficulty: 3,
      skill: 3,
    }
  };

  export default ow1Data;